### ISSUE TITLE
manage-logs from hourly cron script returns error

### ISSUE THREAD

**Issue by caguiar** [zentyal/zentyal#1812]
Running Zentyal 5.1.1

After I upgraded Antivirus  component, I get an error on every run of the cron job, every hour.

/etc/cron.hourly/90zentyal-manage-logs:
Can't locate object method "throw" via package "Can't locate object method "tableInfo" via package "EBox::AntiVirus" at /usr/share/perl5/EBox/Logs.pm line 321.
" (perhaps you forgot to load "Can't locate object method "tableInfo" via package "EBox::AntiVirus" at /usr/share/perl5/EBox/Logs.pm line 321.
"?) at /usr/share/zentyal/manage-logs line 31.
run-parts: /etc/cron.hourly/90zentyal-manage-logs exited with return code 25

**Comment by jacalvo** [comment]
This should be fixed now in Zentyal 6.0, which comes with several improvements in zentyal-antivirus.

**Comment by rmmayer** [comment]
Still present in an Server updated from 4.2 to 5.0 to 6.0
Any hints appreciated as this comes every hour to our Inboxes.

**Comment by covex** [comment]
This is fresh on Z6.0.x

/etc/cron.hourly/90zentyal-manage-logs:
Can't locate object method "throw" via package "Can't locate object method "tableInfo" via package
"EBox::AntiVirus" at /usr/share/perl5/EBox/Logs.pm line 321.
" (perhaps you forgot to load "Can't locate object method "tableInfo" via package "EBox::AntiVirus"
at /usr/share/perl5/EBox/Logs.pm line 321.
"?) at /usr/share/zentyal/manage-logs line 31.
run-parts: /etc/cron.hourly/90zentyal-manage-logs exited with return code 25

How this is supposed to be fixed?
