### ISSUE TITLE
Additional domain controller failed to join domain

### ISSUE THREAD

**Issue by stefanmikroe** [zentyal/zentyal#1845]
Hi guys,

I have installed two Zentyal 6.0 servers, one as PDC and the second one as ADC. In first one, PDC, I created a domain. When I try to join the domain from ADC to PDC, i'm getting the samba error. 
You can see piece of a zentyal.log:

---------------
 GENSEC backend 'krb5' registered
 GENSEC backend 'fake_gssapi_krb5' registered
 Cannot do GSSAPI to an IP address
---------------
tdb(/var/lib/samba/private/secrets.tdb): tdb_open_ex: could not open file /var/lib/samba/private/secrets.tdb: No such file or directory
 Could not open tdb: No such file or directory
 ldb_wrap open of secrets.ldb
 Could not find machine account in secrets database: Failed to fetch machine account password from secrets.ldb: Could not find entry to match filter: '(&(flatname=STEFAN)(objectclass=primaryDomain))' base: 'cn=Primary Domains': No such object: dsdb_search at ../source4/dsdb/common/util.c:4636 and failed to open /var/lib/samba/private/secrets.tdb: NT_STATUS_CANT_ACCESS_DOMAIN_INFO

I also configured krb5.conf as follows:
-----------------------------------------
[libdefaults]
        default_realm = STEFAN.LAN
        dns_lookup_kdc = true
        dns_lookup_realm = true
        rdns = no

Thank you in advance!

**Comment by tjspann** [comment]
I also had this issue, though for what it's worth I'm setting mine up with ADC over OpenVPN if that helps at all.

**Comment by ProBackup-nl** [comment]
I am seeing the same issue:

```
Could not find machine account in secrets database: Failed to fetch machine account password for NETBIOS_DOMAIN_NAME from both secrets.ldb (Could not find entry to match filter: '(&(flatname=NETBIOS_DOMAIN_NAME)(objectclass=primaryDomain))' base: 'cn=Primary Domains': No such object: dsdb_search at ../source4/dsdb/common/util.c:4636) and from /var/lib/samba/private/secrets.tdb: NT_STATUS_CANT_ACCESS_DOMAIN_INFO

 ERROR(runtime): uncaught exception - (9003, 'WERR_DNS_ERROR_RCODE_NAME_ERROR')
```

when trying to add Zentyal as BDC to a PDC that is running Windows 2008 R2. Note Zentyal "Domain Controller and File Sharing" is version 6.0.1.

**Could not retrieve time from AD server 10.0.0.31 via NTP.**
PS It would already be nice when Samba would try to retrieve the time only from the supplied IP of the PDC, and not the IP's that are assigned to VPN servers running on top of that machine.

**Comment by brunolorente** [comment]
This is probably related with a duplicate hostname or... password mistake.
Closing this ticket.

**Comment by Neustradamus** [comment]
@stefanmikroe, @tjspann, @ProBackup-nl: It is solved?

**Comment by imrelaszlo** [comment]
@Neustradamus Same problem here. Did you find out what was the problem? I've completely re-installedd zentyal last night, but I still cannot connect it to a Windows Server 2019 Essenetials DC. DC forest / domain functional level is 2008 R2. 

Cannot do GSSAPI to an IP address
Could not find machine account in secrets database: Failed to fetch machine account password from secrets.ldb: Could not find entry to match filter: '(&(flatname=MYDOMAINNAME)(objectclass=primaryDomain))' base: 'cn=Primary Domains': No such object: dsdb_search at ../source4/dsdb/common/util.c:4636 and failed to open /var/lib/samba/private/secrets.tdb: NT_STATUS_CANT_ACCESS_DOMAIN_INFO

Same issue here: https://forum.zentyal.org/index.php?topic=32536.0

**Comment by Neustradamus** [comment]
@brunolorente: Can you look for a real solution, please reopen this ticket and do not close ticket before solution?

**Comment by imrelaszlo** [comment]
> 
> 
> @Neustradamus Same problem here. Did you find out what was the problem? I've completely re-installedd zentyal last night, but I still cannot connect it to a Windows Server 2019 Essenetials DC. DC forest / domain functional level is 2008 R2.
> 
> Cannot do GSSAPI to an IP address
> Could not find machine account in secrets database: Failed to fetch machine account password from secrets.ldb: Could not find entry to match filter: '(&(flatname=MYDOMAINNAME)(objectclass=primaryDomain))' base: 'cn=Primary Domains': No such object: dsdb_search at ../source4/dsdb/common/util.c:4636 and failed to open /var/lib/samba/private/secrets.tdb: NT_STATUS_CANT_ACCESS_DOMAIN_INFO
> 
> Same issue here: https://forum.zentyal.org/index.php?topic=32536.0
> 
> Some additinal info that I searched for, hope it helps someone:
> 
> [msktutil/msktutil#124](https://github.com/msktutil/msktutil/issues/124)
> https://bugzilla.samba.org/show_bug.cgi?id=13577

In my case, the problem was with the primary DC. After I un/reinstalled domain controller role and review all setting (DNS!) I can join Zentyal as an additional DC.

**Comment by Neustradamus** [comment]
@imrelaszlo: So the problem was the primary DC?
What have you changed exactly?

**Comment by imrelaszlo** [comment]
> 
> 
> @imrelaszlo: So the problem was the primary DC?
> What have you changed exactly?

I don't know what was the exact problem. Maybe with DNS service. When the primary DC was installed, DNS role was preinstalled with the domain as forward lookup zone if I remember correctly. AD integration was set up later. Records are updated, but now I see, _mscds records are not in the same structure. Additional info: first installation created with default forest / domain level, and before I tried to join Zentyal, domain functional level was decreased to 2008R2. When I recreated the domain, this setting was good for the first time. Hope this helps.

**Comment by Neustradamus** [comment]
@imrelaszlo: Thanks! :)

It is not possible to have temp VMs with the same environnement/problem?

@brunolorente can you look?

**Comment by imrelaszlo** [comment]
> 
> 
> @imrelaszlo: Thanks! :)
> 
> It is not possible to have temp VMs with the same environnement/problem?
> 
> @brunolorente can you look?

Sorry, the servers was phaysical ones, and now they are in production. :( The primary DC OS was Win 2019 Essentials for additional info.

**Comment by stefanmikroe** [comment]
I just found a different way. Skipped the pre-conf(domain join) on installation and later I have configure it.

**Comment by Neustradamus** [comment]
@stefanmikroe: Thanks for your remark!
@brunolorente: can you see the problem?

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89, @testdeploys: Have you looked?

**Comment by RaNd250** [comment]
Had the same issue, with 6.0, 6.1 and 6.2.
It turns out that my domain was upgraded from 2003 to 2008R2 and the 2003 level has some changes with the DNS.
I've read somewhere that previous versions of Samba are working fine, so I used Zentyal 5.1 to join the domain with success!!

Right now I'm upgrading from 5.1 to 6, to see if samba is still operational.

**Comment by theroch** [comment]
We have a very similar problem while adding an additional zentyal 7.0 to an existing windows 2011 sbs domain.

Because this is one of the tickets I've found describing this issue and I lost a lot of hours resolving it, here is the solution:
Solution:
It is only possible to join the domain if the msdcs zone is configured to ForestDnsZone and the main domain is configured to DomainDnsZone.
But this is in windows DNS settings configurable.
After I changed line 1196 of the join.py from "dns_partition=domaindns_zone_dn)" to "dns_partition=forestdns_zone_dn)", the join process ended successfully.

Who is interested in more detail can look to samba [bug report](https://bugzilla.samba.org/show_bug.cgi?id=13298)

**Comment by Neustradamus** [comment]
Maybe good to create a new ticket?

**Comment by theroch** [comment]
> Maybe good to create a new ticket?
This bug is not a zentyal bug, it is a bug in the underlying samba core.
I've added already some more informations on the samba wiki to describe this issue and there is already a bug report in the samba bug reporting system, so I don't think we need a new ticket here.

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: It is not possible to add a feature to select the good configuration in the file?

From @theroch: After I changed line 1196 of the join.py from "dns_partition=domaindns_zone_dn)" to "dns_partition=forestdns_zone_dn)", the join process ended successfully.
- https://github.com/zentyal/zentyal/issues/1845#issuecomment-778619330
