### ISSUE TITLE
6.1 Broke new DNS entries

### ISSUE THREAD

**Issue by burkeazbill** [zentyal/zentyal#1925]
**Describe the bug**
Prior to the 6.1 release, using the Zentyal web interface to add a new DNS entry resulted in being able to resolve entries. Now, the entry is added to the web ui, but NOT added to the actual zone file (have only tested/verified with AD integrated zone).

**To Reproduce**
1. Go to DNS
2. Add new host entry with valid IP
3. Save changes
4. Attempt to resolve newly added entry with ping or nslookup
5. Attempt to reverse lookup the newly added entry with nslookup

**Expected behavior**
ping and/or nslookup should result in a valid response for the newly added entry

**Screenshots**
n/a

**Zentyal OS (please complete the following information):**
 - Version: [6.1]
 - Version of the module which has the bug [DNS]
 - Modules installed [Network, Firewall, DNS, FTP, Logs, NTP, DC, Mail, SOGo Webmail]

**Other OS (please complete the following information):**
n/a

**Additional context**
Unanswered forum threads regarding this issue from multiple users:
https://forum.zentyal.org/index.php/topic,34771.msg113042.html
https://forum.zentyal.org/index.php/topic,34752.0.html

**Comment by Neustradamus** [comment]
@burkeazbill: It is solved now?

**Comment by burkeazbill** [comment]
@Neustradamus - I have not had an opportunity to check the 6.1.1 ... It seems that brunolorente closed this and linked a change.. I don't see how/why that change would resolve this issue. I had to re-deploy 6.0 and will NOT upgrade without a pre-upgrade Snapshot (VMware) of the VM running this.

**Comment by sat-dish** [comment]
Changing "allow_duplicated_ips = yes" does not fix this issue. You still can not resolve new DNS entries, but it does fix the #1920 issue.

**Comment by Neustradamus** [comment]
@burkeazbill: Thanks for your reply!
@sat-dish: We are okay, it is for this that I have done my comment ^^
Several times, tickets are closed before the solution, it is not good.

**Comment by Stibila** [comment]
This is not yet fixed and issue should not be closed.
I installed new Zentyal server today and spent hours debugging this issue. Until this is fixed, I found that temporary solution is to manually add DNS entries to samba either with samba tool, or from any Windows machine with DNS Server Tools (part of RSAT).

**Comment by stetho** [comment]
> Changing "allow_duplicated_ips = yes" does not fix this issue. You still can not resolve new DNS entries, but it does fix the #1920 issue.
> Maybe @brunolorente can elaborate on what semmantic versioning change was made?
> I downloaded this as a replacement for Microsoft AD last week and have been banging my head against the wall trying to figure out why this wasn't working. I'm either going to downgrade and start over with my config and follow @burkeazbill suggestion of a snapshot before upgrading, or bite the bullet and purchase Server 2016 as this bug is a showstopper for me.

It is ridiculous that 
1) This bug got through the testing
2) This bug makes Zentyal unusable but they don't seem to care.
3) I'm hoping that closing this bug was a mistake because the fix does nothing.

**Comment by brunolorente** [comment]
Hi everyone,

The bug was caused by a control versioning mistake in our repository, we publish a package which have different code than github, in october, we make changes that affects to DNS module and DDNS feature... these changes weren't uploaded to our packages repository...

We just publish a new package a minute ago with the right code, we have tested it and the bug is fexed.

Sorry for all the inconveniences and many thanks for your time

**Comment by brunolorente** [comment]
As additional info... you need to update the dns module from your Zentyal machine to check the fix

**Comment by Neustradamus** [comment]
@brunolorente: Thanks for your reply!
Have you checked other code too?
If you have done other changes which are not in this repository?
But how it is possible to have a code which is not here?

**Comment by brunolorente** [comment]
@Neustradamus there is no other code repository, I mean the package(apt) repository. The changes applied in the commit 5196c981bc077e148118180dd29587d603f89264 weren't applied properly to the apt repository, so I have taken advantage of the small change in commit 68f2b755aca6c202f7fb384bff11f48e5d2f9ba7 to increase the dns package version, by this way, you will be able to update the package from your Zentyal GUIs fixing the issue.

**Comment by Stibila** [comment]
Thanks, I just upgraded and it is fixed. This could be explained better, I didn't think to do another apt upgrade, since I installed and upgraded fresh server short time before new release was pushed to apt repo.
