### ISSUE TITLE
Config backup fails

### ISSUE THREAD

**Issue by arakan94** [zentyal/zentyal#2025]
**Describe the bug**
Creating config backup from web administration fails with following error:
`root command tar cf /var/lib/zentyal/conf//eboxbackup.tar -C /var/lib/zentyal/conf//backup.PpI4lc eboxbackup --preserve-permissions --exclude eboxbackup/files.tgz 2>&1 failed. Error output: Command output: tar: The following options were used after any non-optional arguments in archive create or update mode. These options are positional and affect only arguments that follow them. Please, rearrange them properly. tar: --exclude âeboxbackup/files.tgzâ has no effect tar: Exiting with failure status due to previous errors . Exit value: 2`

**Screenshots**
![image](https://user-images.githubusercontent.com/11041006/106245143-4adc1900-620c-11eb-8bfd-2d38601566af.png)

**Zentyal OS (please complete the following information):**
 - Version: 7.0
 - DNS, DC, DHCP

**Comment by djoven89** [comment]
Hi @arakan94 ,

This bug was fixed in [this](https://github.com/zentyal/zentyal/commit/3a5341af84999f0c5a4d3d4c6af248380341a843) commit. 

Also, I did a few tests using the official [Zentyal 7.0 Development ISO](http://download.zentyal.com/zentyal-7.0-development-amd64.iso) and it worked correctly.

Best regards, Daniel Joven.

**Comment by arakan94** [comment]
Thanks for reply @djoven89,
my installation was done in beta phase and the issue still persists even with all available updates being installed.

How can I switch to full release? Is there different repository?

**Comment by djoven89** [comment]
Hi @arakan94 ,

I'm affraid that the safest way is to reinstall the Zentyal 7.0 server using the stable ISO. Otherwise, you will need to check if the modules that you are using have been updated, and in case they were updated, you will need to download the packages from the repository and reinstall them, however, this process could cause issues.

Another alternative that you could try is:

1. Fix the issue regarding the configuration backup (just adjust the code and run the command `sudo zs webadmin restart` to apply the changes).

2. Generate a configuration backup and download it.

3. Reinstall the Zentyal 7.0 server using the proper ISO.

4. Restore the configuration backup in the new installation (remember to read the considerations section from the documentation, [here](https://doc.zentyal.org/en/backup-conf.html#considerations-when-restoring-a-configuration-backup) you have the link.

Hope it helps.

Best regards, Daniel Joven.

**Comment by arakan94** [comment]
Does this backup process also restores domain (users, GPOs, joined computers, etc.)?

**Comment by arakan94** [comment]
@djoven89 Tried restoring the config in new installation and got following error:
![image](https://user-images.githubusercontent.com/11041006/107055097-38944900-67d1-11eb-9dff-fe5b974c361b.png)

**Comment by arakan94** [comment]
Also got some, seemingly unrelated issues with DNS - `ping: google.com: Temporary failure in name resolution`

From looking at zentyal.log, there seems to be issue with it right after clean install (before restoring the configuration):
`root command kinit -k -t /var/lib/samba/private/dns.keytab dns-adc failed. 
Error output: kinit: krb5_get_init_creds: unable to reach any KDC in realm DAITE.LAN`

After restoring the configuration, I am getting fails on nsupdate (and saving changes in DNS in webmin throws error):
`root command nsupdate -g -t 10 /var/lib/zentyal/tmp/SHieBv_Tna failed. 
Error output: update failed: REFUSED`

[zentyal.log](https://github.com/zentyal/zentyal/files/5933757/zentyal.log)

**Comment by djoven89** [comment]
Hi @arakan94 ,

I could reproduce your error, it seems that there is a bug with the backup restoration. Developers Team have been notified and as soon as possible they will analyze it.

Related to your current situation, my recommendation is: reinstall the whole Zentyal server and configure again each module. I know that this recommendation is not the best, but sincerely, if was my server, I would prefer to reinstall and configure everything again instead of analyzing and solving the issues that the importation has caused in the server.

I'm sorry for the news.

**Comment by arakan94** [comment]
> 
> 
> Good news @arakan94 we'll publish the fix in a couple of days (max)

That's great news. As it happens, I didn't have time to work on it so far so I can wait and it will help me directly :)

How should I then proceed? Just update and import same config again?

**Comment by Neustradamus** [comment]
@arakan94: Can you confirm that it has been solved?

**Comment by arakan94** [comment]
It's same after running apt update && apt upgrade.. 

Though it seemed to fail somewhat during the upgrade:
Setting up zentyal-samba (7.0.1) ...
 Restarting Zentyal module: samba                                             [fail] 
...
dpkg: cycle found while processing triggers:
 chain of packages whose triggers are or may be responsible:
  zentyal-core -> zentyal-core -> zentyal-core -> zentyal-core -> zentyal-core -> zenty
al-core
 packages' pending triggers which are or may be unresolvable:
  zentyal-core: zentyal-core: /usr/lib/ssl
  linux-image-5.4.0-67-generic: linux-update-5.4.0-67-generic
dpkg: error processing package zentyal-core (--configure):
 triggers looping, abandoned

**Comment by Neustradamus** [comment]
@arakan94: Maybe time to create a new ticket?
