### ISSUE TITLE
LDB-Tools Update causes DNS / DHCP / Sync to fail

### ISSUE THREAD

**Issue by akidburn** [zentyal/zentyal#2121]
Hi,
I had to revert to an earlier State today after a normal update prevented DHCP and DNS from functioning.
In my case, whenever i try to restart the modules, i get an error like this:

DNS Error:

2023/03/09 07:37:42 ERROR> Service.pm:969 EBox::Module::Service::restartService - Error restarting service: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones5Nsa04.ldif failed.
Error output:
Command output: .
Exit value: 1
2023/03/09 07:37:42 ERROR> Service.pm:971 EBox::Module::Service::restartService - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones5Nsa04.ldif failed.
2023/03/09 07:37:42 ERROR> RestartService.pm:61 EBox::SysInfo::CGI::RestartService::_process - Restart of DHCP from dashboard failed: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones5Nsa04.ldif failed.
Error output:
Command output: .
Exit value: 1
2023/03/09 07:37:44 INFO> Index.pm:187 EBox::Dashboard::CGI::Index::masonParameters - dashboard1

Sync:

Error output:
Command output: .
Exit value: 1 at /usr/share/perl5/EBox/Sudo.pm line 240
EBox::Sudo::_rootError('/usr/bin/sudo -p sudo: /var/lib/zentyal/tmp/uJgQXHV1HZ.cmd 2> /var/lib/zentyal/tmp/stderr', 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones8rFvEt.ldif', 256, 'ARRAY(0x55cca49d8200)', 'ARRAY(0x55cca49d8290)') called at /usr/share/perl5/EBox/Sudo.pm line 210
EBox::Sudo::_root(1, 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones8rFvEt.ldif') called at /usr/share/perl5/EBox/Sudo.pm line 153
EBox::Sudo::root('ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones8rFvEt.ldif') called at /usr/share/perl5/EBox/Ldap.pm line 251
EBox::Ldap::dn('EBox::Ldap=HASH(0x55cca4c8d8c8)') called at /usr/share/perl5/EBox/Ldap.pm line 293
EBox::Ldap::domainSID('EBox::Ldap=HASH(0x55cca4c8d8c8)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 232
EBox::Samba::SyncDaemon::setACLs('EBox::Samba::SyncDaemon=HASH(0x55cca80319b8)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 345
EBox::Samba::SyncDaemon::run('EBox::Samba::SyncDaemon=HASH(0x55cca80319b8)', 30, 10) called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 362
2023/03/09 08:31:38 INFO> SyncDaemon.pm:340 EBox::Samba::SyncDaemon::run - Samba sync daemon started
2023/03/09 08:31:41 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesLFUXRW.ldif failed.
Error output:
Command output: .
Exit value: 1 at root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesLFUXRW.ldif failed.
Error output:
Command output: .
Exit value: 1 at /usr/share/perl5/EBox/Sudo.pm line 240
EBox::Sudo::_rootError('/usr/bin/sudo -p sudo: /var/lib/zentyal/tmp/zLNWsxgMXO.cmd 2> /var/lib/zentyal/tmp/stderr', 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesLFUXRW.ldif', 256, 'ARRAY(0x557a733082b0)', 'ARRAY(0x557a73308340)') called at /usr/share/perl5/EBox/Sudo.pm line 210
EBox::Sudo::_root(1, 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesLFUXRW.ldif') called at /usr/share/perl5/EBox/Sudo.pm line 153
EBox::Sudo::root('ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesLFUXRW.ldif') called at /usr/share/perl5/EBox/Ldap.pm line 251
EBox::Ldap::dn('EBox::Ldap=HASH(0x557a76921580)') called at /usr/share/perl5/EBox/Ldap.pm line 293
EBox::Ldap::domainSID('EBox::Ldap=HASH(0x557a76921580)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 232
EBox::Samba::SyncDaemon::setACLs('EBox::Samba::SyncDaemon=HASH(0x557a7697c560)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 345
EBox::Samba::SyncDaemon::run('EBox::Samba::SyncDaemon=HASH(0x557a7697c560)', 30, 10) called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 362

Exit value: 1 at /usr/share/perl5/EBox/Sudo.pm line 240
EBox::Sudo::_rootError('/usr/bin/sudo -p sudo: /var/lib/zentyal/tmp/X2qWSHbQAq.cmd 2> /var/lib/zentyal/tmp/stderr', 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesj_Tu2m.ldif', 256, 'ARRAY(0x5653a3c2e6f0)', 'ARRAY(0x5653a3c2e780)') called at /usr/share/perl5/EBox/Sudo.pm line 210
EBox::Sudo::_root(1, 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesj_Tu2m.ldif') called at /usr/share/perl5/EBox/Sudo.pm line 153
EBox::Sudo::root('ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesj_Tu2m.ldif') called at /usr/share/perl5/EBox/Ldap.pm line 251
EBox::Ldap::dn('EBox::Ldap=HASH(0x5653a71f8580)') called at /usr/share/perl5/EBox/Ldap.pm line 293
EBox::Ldap::domainSID('EBox::Ldap=HASH(0x5653a71f8580)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 232
EBox::Samba::SyncDaemon::setACLs('EBox::Samba::SyncDaemon=HASH(0x5653a72919b8)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 345
EBox::Samba::SyncDaemon::run('EBox::Samba::SyncDaemon=HASH(0x5653a72919b8)', 30, 10) called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 362
2023/03/09 08:25:00 INFO> SyncDaemon.pm:340 EBox::Samba::SyncDaemon::run - Samba sync daemon started
2023/03/09 08:25:01 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesEueItT.ldif failed.
Error output:
Command output: .
Exit value: 1 at root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesEueItT.ldif failed.
Error output:
Command output: .

After checking the dpkg logs and reading the changelog of the ldb-tools package, i found that the update to ldb-tools 2:2.4.4-0ubuntu0.20.04.1 removed a number of options from the ldbsearch command, and the old debug-stderr option causes it to error out.

1. Update to latest ldb-tools package while running dns, dhcp, ...
2. Reboot and watch it fail

**Zentyal OS (please complete the following information):**
 - Version: 7.0.5
 - Version of the module which has the bug 
 -- DHCP Server 7.0.2	
 -- DNS Server 7.0.2	
 -- SyncDaemon.pm (no idea what module that belongs to) Version?

 - Modules installed DNS, DHCP, CA, Core, Domain Controller and File Sharing, Firewall, Jabber, NTP, Network Config, Software Management, VPN

Please fix

akidburn

**Comment by andresaw** [comment]
Problems seems to be that ldbsearch doesnt have the commanline argument --debug-stderr 
It seems like --debug-stdout exists but dont know if that has the same output.

**Comment by andresaw** [comment]
Row 250 ./main/samba/src/EBox/Ldap.pm:                  "--debug-stderr 2>/dev/null 1>$ldifFile";
Row 466 ./main/samba/src/EBox/Ldap.pm:                  "--debug-stderr 2>/dev/null 1>$ldifFile";

I would guess that changing those rows with the commandline agruments "--debug-stdout -d 0 2>/dev/null 1>$ldifFile"  would fix it. Now i not a maintainer or have deep knowledge of zentyal core codebase. This might have other consequences.

**Comment by mad-develop** [comment]
+1 we're having the same issue.

**Comment by andresaw** [comment]
The output from the ldbsearch with the above commandline arguments seems to generate some extra output at least on my ubuntu 22.04.5 LTS server.
```
$ ldbsearch -V
Version 4.15.13-Ubuntu
```


```
$ ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn'
GENSEC backend 'gssapi_spnego' registered
GENSEC backend 'gssapi_krb5' registered
GENSEC backend 'gssapi_krb5_sasl' registered
GENSEC backend 'spnego' registered
GENSEC backend 'schannel' registered
GENSEC backend 'naclrpc_as_system' registered
GENSEC backend 'sasl-EXTERNAL' registered
GENSEC backend 'ntlmssp' registered
GENSEC backend 'ntlmssp_resume_ccache' registered
GENSEC backend 'http_basic' registered
GENSEC backend 'http_ntlm' registered
GENSEC backend 'http_negotiate' registered
GENSEC backend 'krb5' registered
GENSEC backend 'fake_gssapi_krb5' registered
# record 1
dn: DC=hostname,DC=compute,DC=internal

# returned 1 records
# 1 entries
# 0 referrals
```

This will also cause error

`2023/03/09 12:21:03 ERROR> Ldap.pm:257 EBox::Ldap::dn - Error loading LDIF. Error message: First line of LDIF entry does not begin with "dn:", Error lines: GENSEC backend 'gssapi_spnego' registered
`
If i add "-d 0" to the commandline i get the expected result 

```
ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' -d 0
# record 1
dn: DC=hostname,DC=compute,DC=internal

# returned 1 records
# 1 entries
# 0 referrals

```

**Comment by theroch** [comment]
Here are the changes fpr Samba 4.15.x
https://wiki.samba.org/index.php/Samba_Features_added/changed

Debug messages default to output to stderr and you can change it with ---debug-stdout

**Comment by djoven89** [comment]
Hi,

The bug was caused by the improvements in the command line of Samba explained [here](https://wiki.samba.org/index.php/Samba_Features_added/changed#Improved_command_line_user_experience), concretely, because of this:

>Previously many tools silently ignored unknown options. To prevent unexpected behavior all tools will now consistently reject unknown options.

We have accepted a PR from @Deslack and merged it to the master branch in [this](https://github.com/zentyal/zentyal/commit/54391c9ee9e5b30153d97b396f541b15ba271e0d) commit, tomorrow morning we will release the package that contains this fix. 

In case you cannot wait for the package, you can edit the file `/usr/share/perl5/EBox/Ldap.pm` and then, restart the Samba and Webadmin modules as follows:

```sh
sudo zs samba restart
sudo zs webadmin restart
```

**NOTA:** The order is important.

Thank you all for your feedback.

**Comment by marneu** [comment]
Thank you 👍

**Comment by djoven89** [comment]
Hi,

Just to inform you that we have released the package `zentyal-samba-7.0.2` that contains the fix for this bug, you can update your domain controller module through Zentyal GUI (`Software Management -> Zentyal components`) as this [image](https://doc.zentyal.org/en/_images/software-comp_list.png) shows. **NOTE:** Remember to update the list by clicking on the button.

Again, thank you all for your contribution.

**Comment by Neustradamus** [comment]
@Deslak PR is:
- https://github.com/zentyal/zentyal/pull/2122

**Comment by siz0pt** [comment]
Hi ,
That solved the issue with the users, but DNS don't. I still can't access the domain or even login the new user.

DNS service it's running, but keep saying element not found.

**Comment by siz0pt** [comment]
Good morning , this is the log :


2023/04/10 11:13:46 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesirMZy3.ldif failed. 
2023/04/10 11:13:57 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesUZuqXW.ldif failed. 
2023/04/10 11:15:09 INFO> Index.pm:187 EBox::Dashboard::CGI::Index::masonParameters - dashboard1
2023/04/10 11:16:44 INFO> Index.pm:187 EBox::Dashboard::CGI::Index::masonParameters - dashboard1
2023/04/10 11:21:20 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesNTMNvg.ldif failed. 
2023/04/10 11:24:53 WARN> Auth.pm:277 EBox::Middleware::Auth::_login - Failed login from: 192.168.1.144
2023/04/10 11:24:53 DEBUG> PAM.pm:83 Authen::Simple::PAM::check - Successfully authenticated user 'odmin' using service 'zentyal'.
2023/04/10 11:24:54 INFO> Index.pm:187 EBox::Dashboard::CGI::Index::masonParameters - dashboard1
2023/04/10 11:25:09 INFO> Service.pm:965 EBox::Module::Service::restartService - Restarting service for module: dns
2023/04/10 11:25:10 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones2wc9BL.ldif failed. 
2023/04/10 11:25:10 ERROR> Service.pm:969 EBox::Module::Service::restartService - Error restarting service: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones2wc9BL.ldif failed. 
Error output: 
Command output: . 
Exit value: 1
2023/04/10 11:25:10 ERROR> Service.pm:971 EBox::Module::Service::restartService - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones2wc9BL.ldif failed. 
2023/04/10 11:25:10 ERROR> RestartService.pm:61 EBox::SysInfo::CGI::RestartService::_process - Restart of DNS from dashboard failed: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s one -b 'CN=MicrosoftDNS,DC=DomainDnsZones,DC=qsps,DC=local' '(objectClass=dnsZone)' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZones2wc9BL.ldif failed. 
Error output: 
Command output: . 
Exit value: 1
2023/04/10 11:25:12 INFO> Index.pm:187 EBox::Dashboard::CGI::Index::masonParameters - dashboard1

**Comment by pcreadycl** [comment]
> Hi,
> 
> Just to inform you that we have released the package `zentyal-samba-7.0.2` that contains the fix for this bug, you can update your domain controller module through Zentyal GUI (`Software Management -> Zentyal components`) as this [image](https://doc.zentyal.org/en/_images/software-comp_list.png) shows. **NOTE:** Remember to update the list by clicking on the button.
> 
> Again, thank you all for your contribution.

Version zentyal-samba-7.0.2 still with bug...
